#include "qcgc.h"

#include "src/config.h"
#include "src/allocator.h"
#include "src/arena.h"
#include "src/bag.h"
#include "src/event_logger.h"
#include "src/gc_state.h"
#include "src/gray_stack.h"
#include "src/hugeblocktable.h"
#include "src/object.h"
#include "src/shadow_stack.h"
#include "src/signal_handler.h"

#include "src/allocator.c"
#include "src/arena.c"
#include "src/bag.c"
#include "src/event_logger.c"
#include "src/gray_stack.c"
#include "src/hugeblocktable.c"
#include "src/qcgc.c"
#include "src/shadow_stack.c"
#include "src/signal_handler.c"
