#!/usr/bin/env python3

import sys
from statistics import mean
from logutils.iterator import LogIterator
from logutils.visitor import LogEventVisitor

class AllocStatVisitor(LogEventVisitor):
    def __init__(self):
        self.allocs = []

    def visit_allocate(self, event):
        self.allocs.append(event.size)

def print_summary(filename):
    log = LogIterator(filename)
    v = AllocStatVisitor()
    for event in log:
        event.accept(v)
    #
    print("Mean: {} cells".format(mean(v.allocs)))

if __name__ == "__main__":
    for filename in sys.argv[1:]:
        print_summary(filename)
